"""Pydantic schemas for LangChain outputs."""

from __future__ import annotations

from pydantic import BaseModel, Field


class LLMVisualizationRecommendation(BaseModel):
    """A visualization recommendation generated by the LLM."""

    chart_type: str = Field(
        description="Recommended visualization chart type."
    )

    columns: list[str] = Field(
        default_factory=list,
        description="Dataset columns to use for the visualization."
    )

    reason: str = Field(
        description="Explanation for why this visualization is suitable."
    )

    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence score between 0 and 1."
    )


class LLMVisualizationResponse(BaseModel):
    """Structured response generated by the visualization LLM."""

    recommendations: list[LLMVisualizationRecommendation] = Field(
        default_factory=list,
        description="List of visualization recommendations."
    )