import streamlit as st
import pandas as pd


# ============================================================
# MAIN REPORT
# ============================================================


def display_report(result):
    """
    Display only the final human-readable EDA report
    generated by Gemini #2.
    """

    st.markdown(
        """
        <style>
        .stApp {
            background: #f7fafc;
        }
        .block-container {
            max-width: 1450px;
            padding-top: 2rem;
            padding-bottom: 4rem;
        }
        .report-hero {
            background: linear-gradient(135deg, #e0f2fe 0%, #f0fdf4 100%);
            border: 1px solid #bae6fd;
            border-radius: 20px;
            padding: 2rem 2.25rem;
            margin-bottom: 1.5rem;
        }
        .report-hero h1 {
            color: #0f172a;
            font-size: 2.25rem;
            margin: 0 0 .35rem 0;
        }
        .report-hero p {
            color: #475569;
            font-size: 1rem;
            margin: 0;
        }
        .section-card {
            background: #ffffff;
            border: 1px solid #e2e8f0;
            border-radius: 16px;
            padding: 1.35rem 1.5rem;
            margin: 1rem 0;
            box-shadow: 0 4px 14px rgba(15, 23, 42, .04);
        }
        .section-card h2 {
            color: #0f766e;
            margin-top: 0;
        }
        .small-label {
            color: #64748b;
            font-size: .78rem;
            font-weight: 700;
            letter-spacing: .04em;
            text-transform: uppercase;
        }
        .small-value {
            color: #0f172a;
            font-size: 1.35rem;
            font-weight: 700;
        }
        .step-card {
            background: #f8fafc;
            border-left: 4px solid #14b8a6;
            border-radius: 10px;
            margin: .55rem 0;
            padding: .8rem 1rem;
        }
        .recommendation-card {
            background: #eff6ff;
            border: 1px solid #bfdbfe;
            border-radius: 12px;
            margin: .65rem 0;
            padding: 1rem 1.1rem;
        }
        .recommendation-card strong {
            color: #1d4ed8;
        }
        </style>
        <div class="report-header">
            <div class="report-hero">
                <h1>EDA Report</h1>
                <p>Clear, evidence-based exploration of your dataset</p>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    display_final_report(result)


# ============================================================
# DATASET OVERVIEW
# ============================================================

def display_dataset_overview(result):
    """
    Display high-level information about the dataset.
    """

    st.header("Dataset Overview")

    raw_profile = result.get("raw_profile") or {}

    row_count = raw_profile.get("row_count", 0)
    column_count = raw_profile.get("column_count", 0)

    columns = raw_profile.get("columns", [])

    numeric_count = 0
    categorical_count = 0
    datetime_count = 0
    boolean_count = 0

    for column in columns:

        inferred_type = str(
            column.get("inferred_type", "")
        ).lower()

        if inferred_type == "numeric":
            numeric_count += 1

        elif inferred_type == "categorical":
            categorical_count += 1

        elif inferred_type == "datetime":
            datetime_count += 1

        elif inferred_type == "boolean":
            boolean_count += 1

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric(
            "Rows",
            f"{row_count:,}",
        )

    with col2:
        st.metric(
            "Columns",
            f"{column_count:,}",
        )

    with col3:
        st.metric(
            "Numeric Columns",
            numeric_count,
        )

    with col4:
        st.metric(
            "Categorical Columns",
            categorical_count,
        )

    col5, col6 = st.columns(2)

    with col5:
        st.metric(
            "Datetime Columns",
            datetime_count,
        )

    with col6:
        st.metric(
            "Boolean Columns",
            boolean_count,
        )


# ============================================================
# DATA QUALITY
# ============================================================

def display_data_quality(result):
    """
    Display dataset quality information.
    """

    st.header("Data Quality")

    raw_profile = result.get("raw_profile") or {}

    null_summary = raw_profile.get(
        "null_summary",
        {},
    )

    total_missing = 0
    columns_with_missing = []

    if isinstance(null_summary, dict):

        total_missing = null_summary.get(
            "total_missing",
            0,
        )

        columns_with_missing = null_summary.get(
            "columns_with_missing",
            [],
        )

    columns = raw_profile.get(
        "columns",
        [],
    )

    if not columns_with_missing:

        for column in columns:

            missing_count = column.get(
                "missing_count",
                0,
            )

            if missing_count and missing_count > 0:

                columns_with_missing.append(
                    {
                        "column": column.get("name"),
                        "missing_count": missing_count,
                        "missing_percentage": column.get(
                            "missing_percentage",
                            0,
                        ),
                    }
                )

    col1, col2 = st.columns(2)

    with col1:

        st.metric(
            "Total Missing Values",
            f"{total_missing:,}",
        )

    with col2:

        st.metric(
            "Columns With Missing Values",
            len(columns_with_missing),
        )

    if columns_with_missing:

        st.subheader("Missing Value Details")

        rows = []

        for item in columns_with_missing:

            if isinstance(item, dict):

                rows.append(
                    {
                        "Column": item.get(
                            "column",
                            "Unknown",
                        ),
                        "Missing Values": item.get(
                            "missing_count",
                            0,
                        ),
                        "Missing %": (
                            f"{item.get('missing_percentage', 0):.2f}%"
                        ),
                    }
                )

        if rows:

            st.dataframe(
                pd.DataFrame(rows),
                use_container_width=True,
                hide_index=True,
            )

    else:

        st.success(
            "No missing values were detected."
        )


# ============================================================
# PREPROCESSING
# ============================================================

def display_preprocessing(result):
    """
    Display preprocessing information in human-readable form.
    """

    st.header("Preprocessing Summary")

    preprocessing = result.get(
        "preprocessing"
    ) or {}

    summary = preprocessing.get(
        "summary",
        {},
    )

    raw_rows = summary.get(
        "raw_row_count",
        0,
    )

    cleaned_rows = summary.get(
        "cleaned_row_count",
        0,
    )

    raw_columns = summary.get(
        "raw_column_count",
        0,
    )

    cleaned_columns = summary.get(
        "cleaned_column_count",
        0,
    )

    changed_columns = summary.get(
        "changed_column_count",
        0,
    )

    col1, col2, col3, col4 = st.columns(4)

    with col1:

        st.metric(
            "Rows Before",
            f"{raw_rows:,}",
        )

    with col2:

        st.metric(
            "Rows After",
            f"{cleaned_rows:,}",
        )

    with col3:

        st.metric(
            "Columns Before",
            f"{raw_columns:,}",
        )

    with col4:

        st.metric(
            "Columns Changed",
            changed_columns,
        )

    st.subheader("Preprocessing Actions")

    execution_log = preprocessing.get(
        "execution_log",
        [],
    )

    if execution_log:

        for step in execution_log:

            if not isinstance(step, dict):
                continue

            action = (
                step.get("action")
                or step.get("operation")
                or step.get("step")
                or "Preprocessing action"
            )

            status = step.get(
                "status",
                "completed",
            )

            message = (
                step.get("message")
                or step.get("description")
                or ""
            )

            if str(status).lower() in {
                "success",
                "completed",
                "complete",
                "executed",
            }:

                st.success(
                    f"✓ {action}"
                    + (
                        f" — {message}"
                        if message
                        else ""
                    )
                )

            else:

                st.info(
                    f"• {action}"
                    + (
                        f" — {message}"
                        if message
                        else ""
                    )
                )

    else:

        st.info(
            "No preprocessing actions were recorded."
        )


# ============================================================
# STATISTICS
# ============================================================

def display_statistics(result):
    """
    Display statistical analysis in readable tables.
    """

    st.header("Statistical Analysis")

    statistics = result.get(
        "statistics"
    ) or {}

    display_numeric_statistics(
        statistics
    )

    display_categorical_statistics(
        statistics
    )

    display_datetime_statistics(
        statistics
    )

    display_boolean_statistics(
        statistics
    )


def display_numeric_statistics(statistics):
    """
    Display numeric column statistics.
    """

    numeric_statistics = statistics.get(
        "numeric_columns",
        {},
    )

    if not numeric_statistics:
        return

    st.subheader("Numeric Variables")

    rows = []

    for column_name, stats in numeric_statistics.items():

        if not isinstance(stats, dict):
            continue

        rows.append(
            {
                "Column": column_name,
                "Mean": _format_number(
                    stats.get("mean")
                ),
                "Median": _format_number(
                    stats.get("median")
                ),
                "Std Dev": _format_number(
                    stats.get("std")
                ),
                "Minimum": _format_number(
                    stats.get("minimum")
                ),
                "Maximum": _format_number(
                    stats.get("maximum")
                ),
                "Outliers": stats.get(
                    "outlier_count",
                    0,
                ),
            }
        )

    if rows:

        st.dataframe(
            pd.DataFrame(rows),
            use_container_width=True,
            hide_index=True,
        )


def display_categorical_statistics(statistics):
    """
    Display categorical column statistics.
    """

    categorical_statistics = statistics.get(
        "categorical_columns",
        {},
    )

    if not categorical_statistics:
        return

    st.subheader("Categorical Variables")

    rows = []

    for column_name, stats in categorical_statistics.items():

        if not isinstance(stats, dict):
            continue

        rows.append(
            {
                "Column": column_name,
                "Unique Values": stats.get(
                    "unique_count",
                    0,
                ),
                "Most Frequent": stats.get(
                    "top",
                    "-",
                ),
                "Frequency": stats.get(
                    "top_frequency",
                    0,
                ),
                "Top %": _format_percentage(
                    stats.get(
                        "top_percentage"
                    )
                ),
            }
        )

    if rows:

        st.dataframe(
            pd.DataFrame(rows),
            use_container_width=True,
            hide_index=True,
        )


def display_datetime_statistics(statistics):
    """
    Display datetime statistics.
    """

    datetime_statistics = statistics.get(
        "datetime_columns",
        {},
    )

    if not datetime_statistics:
        return

    st.subheader("Datetime Variables")

    rows = []

    for column_name, stats in datetime_statistics.items():

        if not isinstance(stats, dict):
            continue

        rows.append(
            {
                "Column": column_name,
                "Minimum": stats.get(
                    "minimum",
                    "-",
                ),
                "Maximum": stats.get(
                    "maximum",
                    "-",
                ),
                "Unique Values": stats.get(
                    "unique_count",
                    0,
                ),
                "Duration (days)": _format_number(
                    stats.get(
                        "duration_days"
                    )
                ),
            }
        )

    if rows:

        st.dataframe(
            pd.DataFrame(rows),
            use_container_width=True,
            hide_index=True,
        )


def display_boolean_statistics(statistics):
    """
    Display boolean statistics.
    """

    boolean_statistics = statistics.get(
        "boolean_columns",
        {},
    )

    if not boolean_statistics:
        return

    st.subheader("Boolean Variables")

    rows = []

    for column_name, stats in boolean_statistics.items():

        if not isinstance(stats, dict):
            continue

        rows.append(
            {
                "Column": column_name,
                "True Count": stats.get(
                    "true_count",
                    0,
                ),
                "False Count": stats.get(
                    "false_count",
                    0,
                ),
                "True %": _format_percentage(
                    stats.get(
                        "true_percentage"
                    )
                ),
                "False %": _format_percentage(
                    stats.get(
                        "false_percentage"
                    )
                ),
            }
        )

    if rows:

        st.dataframe(
            pd.DataFrame(rows),
            use_container_width=True,
            hide_index=True,
        )


# ============================================================
# VISUALIZATION RECOMMENDATIONS
# ============================================================

def display_visualization_recommendations(result):
    """
    Display LLM-validated visualization recommendations.
    """

    st.header("Visualization Recommendations")

    validation = result.get(
        "visualization_validation"
    ) or {}

    validations = validation.get(
        "validations",
        [],
    )

    if not validations:

        st.info(
            "No visualization recommendations were generated."
        )

        return

    for index, recommendation in enumerate(
        validations,
        start=1,
    ):

        if not isinstance(
            recommendation,
            dict,
        ):
            continue

        decision = recommendation.get(
            "decision",
            "accepted",
        )

        chart_type = (
            recommendation.get(
                "final_chart_type"
            )
            or recommendation.get(
                "original_chart_type"
            )
        )

        columns = (
            recommendation.get(
                "final_columns"
            )
            or recommendation.get(
                "original_columns"
            )
        )

        reason = recommendation.get(
            "reason",
            "No explanation provided.",
        )

        confidence = recommendation.get(
            "confidence",
            0,
        )

        chart_name = _format_chart_name(
            chart_type
        )

        with st.container(
            border=True
        ):

            col1, col2 = st.columns(
                [4, 1]
            )

            with col1:

                st.subheader(
                    f"{index}. {chart_name}"
                )

                if columns:

                    st.write(
                        "**Columns:** "
                        + ", ".join(columns)
                    )

                st.write(
                    f"**Why:** {reason}"
                )

            with col2:

                st.metric(
                    "Confidence",
                    f"{confidence * 100:.0f}%"
                )

                if decision == "accepted":

                    st.success(
                        "Accepted"
                    )

                elif decision == "modified":

                    st.warning(
                        "Modified"
                    )

                elif decision == "rejected":

                    st.error(
                        "Rejected"
                    )


# ============================================================
# FINAL REPORT
# ============================================================


def display_final_report(result):
    """
    Display the final LLM-generated human-readable EDA report.
    """

    final_report = result.get(
        "final_eda_report"
    ) or {}

    if not final_report:
        final_report = _build_report_from_pipeline_result(result)

    raw_dataset = _as_dict(final_report.get("raw_dataset"))
    preprocessing = _as_dict(final_report.get("preprocessing"))
    cleaned_data = (
        _as_dict(final_report.get("cleaned_dataset"))
        or _as_dict(final_report.get("cleaned_data"))
    )
    statistics = (
        _as_dict(final_report.get("statistics"))
        or _as_dict(final_report.get("statistical_information"))
        or _as_dict(result.get("statistics"))
    )
    visualizations = (
        _as_dict(final_report.get("visualizations"))
        or _as_dict(final_report.get("visualization_recommendations"))
        or _as_dict(result.get("visualization_recommendations"))
    )

    _report_section_title("1", "Raw Dataset Information")
    raw_columns = raw_dataset.get("columns") or _typed_columns(raw_dataset)
    raw_profile = _as_dict(result.get("raw_profile"))
    _metric_row([
        ("Rows", raw_dataset.get("row_count", raw_profile.get("row_count", 0))),
        ("Columns", raw_dataset.get("column_count", raw_profile.get("column_count", 0))),
        ("Missing Values", raw_dataset.get("total_missing_count", raw_profile.get("null_summary", {}).get("total_missing", 0))),
        ("Missing %", _format_percentage(raw_dataset.get("total_missing_percentage", 0))),
    ])
    if raw_columns:
        st.dataframe(
            _column_table(raw_columns),
            use_container_width=True,
            hide_index=True,
        )
    _render_warnings(raw_dataset.get("warnings") or [])

    _report_section_title("2", "Preprocessing Steps")
    summary = _as_dict(preprocessing.get("summary"))
    _metric_row([
        ("Rows Before", preprocessing.get("rows_before", summary.get("raw_row_count", summary.get("rows_before", 0)))),
        ("Rows After", preprocessing.get("rows_after", summary.get("cleaned_row_count", summary.get("rows_after", 0)))),
        ("Columns Before", preprocessing.get("columns_before", summary.get("raw_column_count", summary.get("columns_before", 0)))),
        ("Columns After", preprocessing.get("columns_after", summary.get("cleaned_column_count", summary.get("columns_after", 0)))),
    ])
    steps = preprocessing.get("steps") or preprocessing.get("execution_log") or []
    if steps:
        for index, step in enumerate(steps, start=1):
            if isinstance(step, dict):
                action = step.get("action") or step.get("operation") or "Preprocessing action"
                detail = step.get("message") or step.get("reason") or step.get("description") or ""
                status = str(step.get("status", "completed")).replace("_", " ").title()
            else:
                action, detail, status = str(step), "", "Completed"
            st.markdown(
                f'<div class="step-card"><b>{index}. {action}</b>'
                f'<br><span class="small-label">{status}</span>'
                f'{"<br>" + detail if detail else ""}</div>',
                unsafe_allow_html=True,
            )
    else:
        st.info("No preprocessing steps were recorded.")

    _report_section_title("3", "Cleaned Dataset Information")
    cleaned_columns = cleaned_data.get("columns") or []
    cleaned_rows = cleaned_data.get("row_count", preprocessing.get("rows_after", summary.get("cleaned_row_count", 0)))
    cleaned_count = cleaned_data.get("column_count", preprocessing.get("columns_after", summary.get("cleaned_column_count", 0)))
    _metric_row([
        ("Rows", cleaned_rows),
        ("Columns", cleaned_count),
        ("Missing Values", cleaned_data.get("total_missing_count", 0)),
        ("Rows Removed", max(0, preprocessing.get("rows_before", summary.get("raw_row_count", cleaned_rows)) - cleaned_rows)),
    ])
    excluded = cleaned_data.get("excluded_columns") or preprocessing.get("excluded_columns") or []
    removed_columns = len(excluded)
    if removed_columns:
        st.info(f"{removed_columns} column(s) excluded during preprocessing: {_join_items(excluded)}")
    if cleaned_columns:
        st.dataframe(_column_table(cleaned_columns), use_container_width=True, hide_index=True)
    for label, values in [
        ("Unresolved columns", preprocessing.get("unresolved_columns")),
        ("Columns needing review", preprocessing.get("needs_review_columns")),
    ]:
        if values:
            st.warning(f"{label}: {_join_items(values)}")

    _report_section_title("4", "Statistical Information")
    _render_statistics(statistics)

    _report_section_title("5", "Visualization Recommendations")
    recommendations = (
        visualizations.get("selected")
        or visualizations.get("recommendations")
        or []
    )
    if recommendations:
        for index, item in enumerate(recommendations, start=1):
            if isinstance(item, dict):
                chart = _format_chart_name(item.get("chart_type") or item.get("type"))
                columns = _join_items(item.get("columns") or item.get("visualizations") or [])
                reason = item.get("reason") or "Useful for exploring the selected variables."
                priority = str(item.get("priority", "medium")).title()
                confidence = item.get("confidence")
                confidence_text = (
                    f" · Confidence: {_format_percentage(float(confidence) * 100)}"
                    if confidence is not None else ""
                )
                body = f"<b>{index}. {chart}</b> · {priority}{confidence_text}<br>"
                body += f"<span>Columns: {columns or 'Selected dataset variables'}</span><br>{reason}"
            else:
                body = f"<b>{index}. Recommendation</b><br>{item}"
            st.markdown(f'<div class="recommendation-card">{body}</div>', unsafe_allow_html=True)
    else:
        st.info("No visualization recommendations were produced.")

# ============================================================
# FINAL REPORT DISPLAY HELPERS
# ============================================================

def _as_dict(value):
    """Keep legacy text fields from breaking structured report rendering."""
    return value if isinstance(value, dict) else {}


def _build_report_from_pipeline_result(result):
    """Render deterministic backend evidence when the narrative model is unavailable."""
    raw_profile = _as_dict(result.get("raw_profile"))
    preprocessing = _as_dict(result.get("preprocessing"))
    statistics = _as_dict(result.get("statistics"))
    recommendations = _as_dict(result.get("visualization_recommendations"))
    return {
        "raw_dataset": {
            "row_count": raw_profile.get("row_count", 0),
            "column_count": raw_profile.get("column_count", 0),
            "columns": raw_profile.get("columns", []),
            "total_missing_count": (
                _as_dict(raw_profile.get("null_summary"))
                .get("total_missing", 0)
            ),
        },
        "preprocessing": preprocessing,
        "cleaned_data": {
            "row_count": (
                preprocessing.get("rows_after", 0)
                if isinstance(preprocessing, dict)
                else 0
            ),
            "column_count": (
                preprocessing.get("columns_after", 0)
                if isinstance(preprocessing, dict)
                else 0
            ),
            "excluded_columns": preprocessing.get("excluded_columns", []),
        },
        "statistical_information": statistics,
        "visualization_recommendations": recommendations,
    }


def _typed_columns(report):
    """Build a readable column table from the compact final-report schema."""
    columns = []
    for field, inferred_type in [
        ("numeric_columns", "numeric"),
        ("categorical_columns", "categorical"),
        ("datetime_columns", "datetime"),
        ("boolean_columns", "boolean"),
    ]:
        for name in report.get(field) or []:
            columns.append({
                "name": name,
                "semantic_type": inferred_type,
            })
    return columns


def _report_section_title(number, title):
    st.markdown(
        f'<div class="section-card"><h2>{number}. {title}</h2></div>',
        unsafe_allow_html=True,
    )


def _metric_row(metrics):
    columns = st.columns(len(metrics))
    for container, (label, value) in zip(columns, metrics):
        with container:
            display_value = value if isinstance(value, str) else _format_number(value)
            st.markdown(
                f'<div class="small-label">{label}</div>'
                f'<div class="small-value">{display_value}</div>',
                unsafe_allow_html=True,
            )


def _join_items(values):
    names = []
    for value in values or []:
        if isinstance(value, dict):
            names.append(
                str(value.get("column") or value.get("name") or value.get("action") or value)
            )
        else:
            names.append(str(value))
    return ", ".join(names) if names else "-"


def _column_table(columns):
    rows = []
    for column in columns:
        if not isinstance(column, dict):
            continue
        rows.append({
            "Column": column.get("name") or column.get("column") or "-",
            "Data type": column.get("dtype") or column.get("inferred_type") or column.get("semantic_type") or "-",
            "Inferred type": column.get("semantic_type") or column.get("inferred_type") or "-",
            "Non-null": column.get("non_null_count", column.get("count", "-")),
            "Missing": column.get("null_count", column.get("missing_count", "-")),
            "Unique": column.get("unique_count", "-"),
        })
    return pd.DataFrame(rows)


def _render_warnings(warnings):
    for warning in warnings:
        text = warning.get("message", warning) if isinstance(warning, dict) else warning
        st.warning(str(text))


def _render_statistics(statistics):
    sections = [
        ("Numeric variables", statistics.get("numeric_statistics") or statistics.get("numeric_columns") or [],
         ["mean", "median", "std", "minimum", "maximum", "outlier_count"]),
        ("Categorical variables", statistics.get("categorical_statistics") or statistics.get("categorical_columns") or [],
         ["unique_count", "top", "top_frequency", "top_percentage"]),
        ("Datetime variables", statistics.get("datetime_statistics") or statistics.get("datetime_columns") or [],
         ["minimum", "maximum", "unique_count", "duration_days"]),
        ("Boolean variables", statistics.get("boolean_statistics") or statistics.get("boolean_columns") or [],
         ["true_count", "false_count", "true_percentage", "false_percentage"]),
    ]
    labels = {
        "mean": "Mean", "median": "Median", "std": "Std. Dev.",
        "minimum": "Minimum", "maximum": "Maximum", "outlier_count": "Outliers",
        "unique_count": "Unique", "top": "Most frequent", "top_frequency": "Frequency",
        "top_percentage": "Top %", "duration_days": "Duration (days)",
        "true_count": "True", "false_count": "False",
        "true_percentage": "True %", "false_percentage": "False %",
    }
    for title, values, fields in sections:
        if not values:
            continue
        st.markdown(f"**{title}**")
        rows = []
        for name, item in values.items() if isinstance(values, dict) else []:
            if not isinstance(item, dict):
                continue
            row = {"Column": name}
            for field in fields:
                if field in item:
                    value = item[field]
                    row[labels[field]] = (
                        _format_percentage(value) if "percentage" in field else _format_number(value)
                    )
            rows.append(row)
        if rows:
            st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)
    correlation = statistics.get("correlation_matrix") or {}
    if correlation:
        with st.expander("View correlation matrix"):
            st.dataframe(pd.DataFrame(correlation), use_container_width=True)


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def _format_number(value):
    """
    Format numeric values for display.
    """

    if value is None:
        return "-"

    if isinstance(
        value,
        (int, float),
    ):

        if isinstance(
            value,
            float,
        ):

            return f"{value:,.2f}"

        return f"{value:,}"

    return str(value)


def _format_percentage(value):
    """
    Format percentage values.
    """

    if value is None:
        return "-"

    try:

        return f"{float(value):.2f}%"

    except (
        TypeError,
        ValueError,
    ):

        return str(value)


def _format_chart_name(chart_type):
    """
    Convert technical chart names into
    human-readable names.
    """

    if not chart_type:
        return "Visualization"

    mapping = {
        "histogram": "Histogram",
        "box_plot": "Box Plot",
        "bar_chart": "Bar Chart",
        "pie_chart": "Pie Chart",
        "pie_donut_chart": "Pie / Donut Chart",
        "scatter_plot": "Scatter Plot",
        "line_chart": "Line Chart",
        "grouped_bar_chart": "Grouped Bar Chart",
        "stacked_bar_chart": "Stacked Bar Chart",
        "100_percent_stacked_bar_chart": (
            "100% Stacked Bar Chart"
        ),
        "heatmap": "Correlation Heatmap",
        "correlation_heatmap": (
            "Correlation Heatmap"
        ),
        "missingness_bar_chart": (
            "Missingness Bar Chart"
        ),
        "missingness_heatmap": (
            "Missingness Heatmap"
        ),
        "violin_plot": "Violin Plot",
        "qq_plot": "Q-Q Plot",
        "pair_plot": "Pair Plot",
    }

    return mapping.get(
        chart_type,
        str(chart_type).replace(
            "_",
            " ",
        ).title(),
    )