import streamlit as st
import pandas as pd


# ============================================================
# MAIN REPORT
# ============================================================


def display_report(result):
    """
    Display only the final human-readable EDA report
    generated by Gemini #2.
    """

    st.markdown(
        """
        <div class="report-header">
            <h1>EDA Report</h1>
            <p>Automated Exploratory Data Analysis</p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    display_final_report(result)


# ============================================================
# DATASET OVERVIEW
# ============================================================

def display_dataset_overview(result):
    """
    Display high-level information about the dataset.
    """

    st.header("Dataset Overview")

    raw_profile = result.get("raw_profile") or {}

    row_count = raw_profile.get("row_count", 0)
    column_count = raw_profile.get("column_count", 0)

    columns = raw_profile.get("columns", [])

    numeric_count = 0
    categorical_count = 0
    datetime_count = 0
    boolean_count = 0

    for column in columns:

        inferred_type = str(
            column.get("inferred_type", "")
        ).lower()

        if inferred_type == "numeric":
            numeric_count += 1

        elif inferred_type == "categorical":
            categorical_count += 1

        elif inferred_type == "datetime":
            datetime_count += 1

        elif inferred_type == "boolean":
            boolean_count += 1

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric(
            "Rows",
            f"{row_count:,}",
        )

    with col2:
        st.metric(
            "Columns",
            f"{column_count:,}",
        )

    with col3:
        st.metric(
            "Numeric Columns",
            numeric_count,
        )

    with col4:
        st.metric(
            "Categorical Columns",
            categorical_count,
        )

    col5, col6 = st.columns(2)

    with col5:
        st.metric(
            "Datetime Columns",
            datetime_count,
        )

    with col6:
        st.metric(
            "Boolean Columns",
            boolean_count,
        )


# ============================================================
# DATA QUALITY
# ============================================================

def display_data_quality(result):
    """
    Display dataset quality information.
    """

    st.header("Data Quality")

    raw_profile = result.get("raw_profile") or {}

    null_summary = raw_profile.get(
        "null_summary",
        {},
    )

    total_missing = 0
    columns_with_missing = []

    if isinstance(null_summary, dict):

        total_missing = null_summary.get(
            "total_missing",
            0,
        )

        columns_with_missing = null_summary.get(
            "columns_with_missing",
            [],
        )

    columns = raw_profile.get(
        "columns",
        [],
    )

    if not columns_with_missing:

        for column in columns:

            missing_count = column.get(
                "missing_count",
                0,
            )

            if missing_count and missing_count > 0:

                columns_with_missing.append(
                    {
                        "column": column.get("name"),
                        "missing_count": missing_count,
                        "missing_percentage": column.get(
                            "missing_percentage",
                            0,
                        ),
                    }
                )

    col1, col2 = st.columns(2)

    with col1:

        st.metric(
            "Total Missing Values",
            f"{total_missing:,}",
        )

    with col2:

        st.metric(
            "Columns With Missing Values",
            len(columns_with_missing),
        )

    if columns_with_missing:

        st.subheader("Missing Value Details")

        rows = []

        for item in columns_with_missing:

            if isinstance(item, dict):

                rows.append(
                    {
                        "Column": item.get(
                            "column",
                            "Unknown",
                        ),
                        "Missing Values": item.get(
                            "missing_count",
                            0,
                        ),
                        "Missing %": (
                            f"{item.get('missing_percentage', 0):.2f}%"
                        ),
                    }
                )

        if rows:

            st.dataframe(
                pd.DataFrame(rows),
                use_container_width=True,
                hide_index=True,
            )

    else:

        st.success(
            "No missing values were detected."
        )


# ============================================================
# PREPROCESSING
# ============================================================

def display_preprocessing(result):
    """
    Display preprocessing information in human-readable form.
    """

    st.header("Preprocessing Summary")

    preprocessing = result.get(
        "preprocessing"
    ) or {}

    summary = preprocessing.get(
        "summary",
        {},
    )

    raw_rows = summary.get(
        "raw_row_count",
        0,
    )

    cleaned_rows = summary.get(
        "cleaned_row_count",
        0,
    )

    raw_columns = summary.get(
        "raw_column_count",
        0,
    )

    cleaned_columns = summary.get(
        "cleaned_column_count",
        0,
    )

    changed_columns = summary.get(
        "changed_column_count",
        0,
    )

    col1, col2, col3, col4 = st.columns(4)

    with col1:

        st.metric(
            "Rows Before",
            f"{raw_rows:,}",
        )

    with col2:

        st.metric(
            "Rows After",
            f"{cleaned_rows:,}",
        )

    with col3:

        st.metric(
            "Columns Before",
            f"{raw_columns:,}",
        )

    with col4:

        st.metric(
            "Columns Changed",
            changed_columns,
        )

    st.subheader("Preprocessing Actions")

    execution_log = preprocessing.get(
        "execution_log",
        [],
    )

    if execution_log:

        for step in execution_log:

            if not isinstance(step, dict):
                continue

            action = (
                step.get("action")
                or step.get("operation")
                or step.get("step")
                or "Preprocessing action"
            )

            status = step.get(
                "status",
                "completed",
            )

            message = (
                step.get("message")
                or step.get("description")
                or ""
            )

            if str(status).lower() in {
                "success",
                "completed",
                "complete",
                "executed",
            }:

                st.success(
                    f"✓ {action}"
                    + (
                        f" — {message}"
                        if message
                        else ""
                    )
                )

            else:

                st.info(
                    f"• {action}"
                    + (
                        f" — {message}"
                        if message
                        else ""
                    )
                )

    else:

        st.info(
            "No preprocessing actions were recorded."
        )


# ============================================================
# STATISTICS
# ============================================================

def display_statistics(result):
    """
    Display statistical analysis in readable tables.
    """

    st.header("Statistical Analysis")

    statistics = result.get(
        "statistics"
    ) or {}

    display_numeric_statistics(
        statistics
    )

    display_categorical_statistics(
        statistics
    )

    display_datetime_statistics(
        statistics
    )

    display_boolean_statistics(
        statistics
    )


def display_numeric_statistics(statistics):
    """
    Display numeric column statistics.
    """

    numeric_statistics = statistics.get(
        "numeric_columns",
        {},
    )

    if not numeric_statistics:
        return

    st.subheader("Numeric Variables")

    rows = []

    for column_name, stats in numeric_statistics.items():

        if not isinstance(stats, dict):
            continue

        rows.append(
            {
                "Column": column_name,
                "Mean": _format_number(
                    stats.get("mean")
                ),
                "Median": _format_number(
                    stats.get("median")
                ),
                "Std Dev": _format_number(
                    stats.get("std")
                ),
                "Minimum": _format_number(
                    stats.get("minimum")
                ),
                "Maximum": _format_number(
                    stats.get("maximum")
                ),
                "Outliers": stats.get(
                    "outlier_count",
                    0,
                ),
            }
        )

    if rows:

        st.dataframe(
            pd.DataFrame(rows),
            use_container_width=True,
            hide_index=True,
        )


def display_categorical_statistics(statistics):
    """
    Display categorical column statistics.
    """

    categorical_statistics = statistics.get(
        "categorical_columns",
        {},
    )

    if not categorical_statistics:
        return

    st.subheader("Categorical Variables")

    rows = []

    for column_name, stats in categorical_statistics.items():

        if not isinstance(stats, dict):
            continue

        rows.append(
            {
                "Column": column_name,
                "Unique Values": stats.get(
                    "unique_count",
                    0,
                ),
                "Most Frequent": stats.get(
                    "top",
                    "-",
                ),
                "Frequency": stats.get(
                    "top_frequency",
                    0,
                ),
                "Top %": _format_percentage(
                    stats.get(
                        "top_percentage"
                    )
                ),
            }
        )

    if rows:

        st.dataframe(
            pd.DataFrame(rows),
            use_container_width=True,
            hide_index=True,
        )


def display_datetime_statistics(statistics):
    """
    Display datetime statistics.
    """

    datetime_statistics = statistics.get(
        "datetime_columns",
        {},
    )

    if not datetime_statistics:
        return

    st.subheader("Datetime Variables")

    rows = []

    for column_name, stats in datetime_statistics.items():

        if not isinstance(stats, dict):
            continue

        rows.append(
            {
                "Column": column_name,
                "Minimum": stats.get(
                    "minimum",
                    "-",
                ),
                "Maximum": stats.get(
                    "maximum",
                    "-",
                ),
                "Unique Values": stats.get(
                    "unique_count",
                    0,
                ),
                "Duration (days)": _format_number(
                    stats.get(
                        "duration_days"
                    )
                ),
            }
        )

    if rows:

        st.dataframe(
            pd.DataFrame(rows),
            use_container_width=True,
            hide_index=True,
        )


def display_boolean_statistics(statistics):
    """
    Display boolean statistics.
    """

    boolean_statistics = statistics.get(
        "boolean_columns",
        {},
    )

    if not boolean_statistics:
        return

    st.subheader("Boolean Variables")

    rows = []

    for column_name, stats in boolean_statistics.items():

        if not isinstance(stats, dict):
            continue

        rows.append(
            {
                "Column": column_name,
                "True Count": stats.get(
                    "true_count",
                    0,
                ),
                "False Count": stats.get(
                    "false_count",
                    0,
                ),
                "True %": _format_percentage(
                    stats.get(
                        "true_percentage"
                    )
                ),
                "False %": _format_percentage(
                    stats.get(
                        "false_percentage"
                    )
                ),
            }
        )

    if rows:

        st.dataframe(
            pd.DataFrame(rows),
            use_container_width=True,
            hide_index=True,
        )


# ============================================================
# VISUALIZATION RECOMMENDATIONS
# ============================================================

def display_visualization_recommendations(result):
    """
    Display LLM-validated visualization recommendations.
    """

    st.header("Visualization Recommendations")

    validation = result.get(
        "visualization_validation"
    ) or {}

    validations = validation.get(
        "validations",
        [],
    )

    if not validations:

        st.info(
            "No visualization recommendations were generated."
        )

        return

    for index, recommendation in enumerate(
        validations,
        start=1,
    ):

        if not isinstance(
            recommendation,
            dict,
        ):
            continue

        decision = recommendation.get(
            "decision",
            "accepted",
        )

        chart_type = (
            recommendation.get(
                "final_chart_type"
            )
            or recommendation.get(
                "original_chart_type"
            )
        )

        columns = (
            recommendation.get(
                "final_columns"
            )
            or recommendation.get(
                "original_columns"
            )
        )

        reason = recommendation.get(
            "reason",
            "No explanation provided.",
        )

        confidence = recommendation.get(
            "confidence",
            0,
        )

        chart_name = _format_chart_name(
            chart_type
        )

        with st.container(
            border=True
        ):

            col1, col2 = st.columns(
                [4, 1]
            )

            with col1:

                st.subheader(
                    f"{index}. {chart_name}"
                )

                if columns:

                    st.write(
                        "**Columns:** "
                        + ", ".join(columns)
                    )

                st.write(
                    f"**Why:** {reason}"
                )

            with col2:

                st.metric(
                    "Confidence",
                    f"{confidence * 100:.0f}%"
                )

                if decision == "accepted":

                    st.success(
                        "Accepted"
                    )

                elif decision == "modified":

                    st.warning(
                        "Modified"
                    )

                elif decision == "rejected":

                    st.error(
                        "Rejected"
                    )


# ============================================================
# FINAL REPORT
# ============================================================


def display_final_report(result):
    """
    Display the final LLM-generated human-readable EDA report.
    """

    st.header("Final EDA Report")

    final_report = result.get(
        "final_eda_report"
    ) or {}

    if not final_report:
        st.info(
            "Final EDA report is not available yet."
        )
        return

    # ========================================================
    # 1. RAW DATA INFORMATION
    # ========================================================

    raw_dataset = final_report.get(
        "raw_dataset",
        {},
    )

    if raw_dataset:

        st.subheader(
            "1. Raw Dataset Information"
        )

        overview = raw_dataset.get(
            "overview",
            "",
        )

        if overview:
            st.write(overview)

        row_count = raw_dataset.get(
            "row_count",
            0,
        )

        column_count = raw_dataset.get(
            "column_count",
            0,
        )

        col1, col2 = st.columns(2)

        with col1:
            st.metric(
                "Rows",
                f"{row_count:,}",
            )

        with col2:
            st.metric(
                "Columns",
                f"{column_count:,}",
            )

        numeric_columns = raw_dataset.get(
            "numeric_columns",
            [],
        )

        categorical_columns = raw_dataset.get(
            "categorical_columns",
            [],
        )

        datetime_columns = raw_dataset.get(
            "datetime_columns",
            [],
        )

        boolean_columns = raw_dataset.get(
            "boolean_columns",
            [],
        )

        missing_value_columns = raw_dataset.get(
            "missing_value_columns",
            [],
        )

        if numeric_columns:
            st.write(
                "**Numeric Columns:** "
                + ", ".join(numeric_columns)
            )

        if categorical_columns:
            st.write(
                "**Categorical Columns:** "
                + ", ".join(categorical_columns)
            )

        if datetime_columns:
            st.write(
                "**Datetime Columns:** "
                + ", ".join(datetime_columns)
            )

        if boolean_columns:
            st.write(
                "**Boolean Columns:** "
                + ", ".join(boolean_columns)
            )

        if missing_value_columns:
            st.write(
                "**Columns With Missing Values:** "
                + ", ".join(missing_value_columns)
            )

    # ========================================================
    # 2. PREPROCESSING STEPS
    # ========================================================

    preprocessing = final_report.get(
        "preprocessing",
        {},
    )

    if preprocessing:

        st.subheader(
            "2. Preprocessing Steps"
        )

        summary = preprocessing.get(
            "summary",
            "",
        )

        if summary:
            st.write(summary)

        rows_before = preprocessing.get(
            "rows_before",
            0,
        )

        rows_after = preprocessing.get(
            "rows_after",
            0,
        )

        columns_before = preprocessing.get(
            "columns_before",
            0,
        )

        columns_after = preprocessing.get(
            "columns_after",
            0,
        )

        col1, col2, col3, col4 = st.columns(4)

        with col1:
            st.metric(
                "Rows Before",
                f"{rows_before:,}",
            )

        with col2:
            st.metric(
                "Rows After",
                f"{rows_after:,}",
            )

        with col3:
            st.metric(
                "Columns Before",
                f"{columns_before:,}",
            )

        with col4:
            st.metric(
                "Columns After",
                f"{columns_after:,}",
            )

        steps = preprocessing.get(
            "steps",
            [],
        )

        if steps:

            st.markdown(
                "**Actions Performed:**"
            )

            for step in steps:
                st.write(
                    f"• {step}"
                )

    # ========================================================
    # 3. CLEANED DATA INFORMATION
    # ========================================================

    cleaned_data = final_report.get(
        "cleaned_data",
        {},
    )

    if cleaned_data:

        st.subheader(
            "3. Cleaned Data Information"
        )

        overview = cleaned_data.get(
            "overview",
            "",
        )

        if overview:
            st.write(overview)

        row_count = cleaned_data.get(
            "row_count",
            0,
        )

        column_count = cleaned_data.get(
            "column_count",
            0,
        )

        col1, col2 = st.columns(2)

        with col1:
            st.metric(
                "Cleaned Rows",
                f"{row_count:,}",
            )

        with col2:
            st.metric(
                "Cleaned Columns",
                f"{column_count:,}",
            )

        retained_columns = cleaned_data.get(
            "retained_columns",
            [],
        )

        excluded_columns = cleaned_data.get(
            "excluded_columns",
            [],
        )

        if retained_columns:

            st.write(
                "**Retained Columns:** "
                + ", ".join(retained_columns)
            )

        if excluded_columns:

            st.write(
                "**Excluded Columns:** "
                + ", ".join(excluded_columns)
            )

    # ========================================================
    # 4. STATISTICAL INFORMATION
    # ========================================================

    statistical_information = final_report.get(
        "statistical_information",
        {},
    )

    if statistical_information:

        st.subheader(
            "4. Statistical Information"
        )

        overview = statistical_information.get(
            "overview",
            "",
        )

        if overview:
            st.write(overview)

        key_findings = statistical_information.get(
            "key_findings",
            [],
        )

        if key_findings:

            st.markdown(
                "**Key Findings:**"
            )

            for finding in key_findings:
                st.write(
                    f"• {finding}"
                )

    # ========================================================
    # 5. VISUALIZATION RECOMMENDATIONS
    # ========================================================

    visualization_recommendations = final_report.get(
        "visualization_recommendations",
        {},
    )

    if visualization_recommendations:

        st.subheader(
            "5. Visualization Recommendations"
        )

        overview = visualization_recommendations.get(
            "overview",
            "",
        )

        if overview:
            st.write(overview)

        recommendations = visualization_recommendations.get(
            "recommendations",
            [],
        )

        if recommendations:

            for index, recommendation in enumerate(
                recommendations,
                start=1,
            ):

                st.write(
                    f"**{index}.** {recommendation}"
                )

# ============================================================
# HELPER FUNCTIONS
# ============================================================

def _format_number(value):
    """
    Format numeric values for display.
    """

    if value is None:
        return "-"

    if isinstance(
        value,
        (int, float),
    ):

        if isinstance(
            value,
            float,
        ):

            return f"{value:,.2f}"

        return f"{value:,}"

    return str(value)


def _format_percentage(value):
    """
    Format percentage values.
    """

    if value is None:
        return "-"

    try:

        return f"{float(value):.2f}%"

    except (
        TypeError,
        ValueError,
    ):

        return str(value)


def _format_chart_name(chart_type):
    """
    Convert technical chart names into
    human-readable names.
    """

    if not chart_type:
        return "Visualization"

    mapping = {
        "histogram": "Histogram",
        "box_plot": "Box Plot",
        "bar_chart": "Bar Chart",
        "pie_chart": "Pie Chart",
        "pie_donut_chart": "Pie / Donut Chart",
        "scatter_plot": "Scatter Plot",
        "line_chart": "Line Chart",
        "grouped_bar_chart": "Grouped Bar Chart",
        "stacked_bar_chart": "Stacked Bar Chart",
        "100_percent_stacked_bar_chart": (
            "100% Stacked Bar Chart"
        ),
        "heatmap": "Correlation Heatmap",
        "correlation_heatmap": (
            "Correlation Heatmap"
        ),
        "missingness_bar_chart": (
            "Missingness Bar Chart"
        ),
        "missingness_heatmap": (
            "Missingness Heatmap"
        ),
        "violin_plot": "Violin Plot",
        "qq_plot": "Q-Q Plot",
        "pair_plot": "Pair Plot",
    }

    return mapping.get(
        chart_type,
        str(chart_type).replace(
            "_",
            " ",
        ).title(),
    )