# The purpose of this file is to define the structure of the final report generated by EDA-Guider.

from pydantic import BaseModel, Field

class Insight(BaseModel):

    title : str 
    description : str
    evidence : dict 

class VisualizationRecommendation(BaseModel):
    chart_type: str
    columns: list[str]
    title: str
    reason: str


class EDAReport(BaseModel):
    dataset_name: str

    summary: str

    insights: list[Insight] = []
    visualizations: list[VisualizationRecommendation] = []

    preprocessing_summary: list[str] = []

    statistics_summary: dict = {}

    hallucination_checked: bool = False